"""설정 상속/병합 로직"""

import copy
import json
from datetime import datetime, timezone
from pathlib import Path

import yaml


def deep_merge(base: dict, override: dict) -> dict:
    """두 dict를 재귀적으로 병합. override 값이 우선.

    - dict: 재귀적으로 병합
    - list: override로 완전 대체
    - scalar: override로 완전 대체
    """
    result = copy.deepcopy(base)
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def merge_text_files(
    root_content: str | None,
    app_content: str | None,
    strategy: str,
    app_name: str,
) -> str:
    """텍스트 파일 병합 (append/prepend/replace)"""
    if strategy == "replace":
        return app_content or ""

    if root_content is None:
        return app_content or ""
    if app_content is None:
        return root_content or ""

    separator = f"\n\n---\n<!-- {app_name} -->\n\n"

    if strategy == "append":
        return root_content + separator + app_content
    elif strategy == "prepend":
        return app_content + separator + root_content
    else:
        # 기본값: append
        return root_content + separator + app_content


def merge_json_files(
    root_content: str | None,
    app_content: str | None,
    strategy: str,
) -> str:
    """JSON 파일 병합 (deep-merge/replace)"""
    if strategy == "replace":
        return app_content or "{}"

    root_data = json.loads(root_content) if root_content else {}
    app_data = json.loads(app_content) if app_content else {}

    merged = deep_merge(root_data, app_data)
    return json.dumps(merged, indent=2, ensure_ascii=False)


def get_merge_strategy(
    filename: str,
    merge_config: dict,
) -> str:
    """파일명에 따른 병합 전략 반환.

    merge_config: agent.config.yaml의 merge 섹션
    기본값: .md → append, .json → deep-merge
    """
    # 명시적 설정이 있으면 사용
    if filename in merge_config:
        return merge_config[filename]

    # 기본값
    suffix = Path(filename).suffix.lower()
    if suffix == ".md":
        return "append"
    elif suffix == ".json":
        return "deep-merge"
    else:
        return "replace"


def generate_header(app_name: str, agent: str) -> str:
    """자동 생성 헤더 (마크다운 주석 형식)"""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!-- AUTO-GENERATED by ConfHub - DO NOT EDIT DIRECTLY -->\n"
        f"<!-- Source: root/agents/{agent} → apps/{app_name}/agents/{agent} -->\n"
        f"<!-- Generated: {now} -->\n\n"
    )


class ConfigMerger:
    """Registry 설정 병합기"""

    def __init__(self, registry_base: Path):
        self.registry_base = registry_base

    def resolve_agent(
        self,
        app_name: str,
        agent: str,
        dry_run: bool = False,
    ) -> dict[str, str]:
        """단일 앱의 단일 에이전트 설정을 병합하여 resolved 경로에 저장.

        Returns:
            {파일명: 병합된 내용} 딕셔너리
        """
        from confhub.core.agents import get_agent

        # 경로 설정
        root_agent_dir = self.registry_base / "root" / "agents" / agent
        app_agent_dir = self.registry_base / "apps" / app_name / "agents" / agent
        resolved_dir = self.registry_base / "resolved" / app_name / agent

        # merge 설정 로드
        root_merge_config = self._load_merge_config(root_agent_dir)
        app_merge_config = self._load_merge_config(app_agent_dir)
        # 앱 설정이 루트 설정을 오버라이드
        merge_config = {**root_merge_config, **app_merge_config}

        # 에이전트 설정 디렉토리 이름 파악
        try:
            agent_cfg = get_agent(agent)
            config_subdir = agent_cfg.config_dir  # ".claude", ".gemini", "." 등
        except ValueError:
            config_subdir = f".{agent}"

        # 소스 디렉토리
        if config_subdir == ".":
            root_src = root_agent_dir
            app_src = app_agent_dir
        else:
            root_src = root_agent_dir / config_subdir
            app_src = app_agent_dir / config_subdir

        # 병합할 파일 목록 (루트 + 앱 파일 합집합)
        all_files: set[str] = set()
        if root_src.exists():
            all_files.update(f.name for f in root_src.rglob("*") if f.is_file())
        if app_src.exists():
            all_files.update(f.name for f in app_src.rglob("*") if f.is_file())

        results: dict[str, str] = {}
        header = generate_header(app_name, agent)

        for filename in sorted(all_files):
            root_file = root_src / filename if root_src.exists() else None
            app_file = app_src / filename if app_src.exists() else None

            root_content = (
                root_file.read_text(encoding="utf-8") if root_file and root_file.exists() else None
            )
            app_content = (
                app_file.read_text(encoding="utf-8") if app_file and app_file.exists() else None
            )

            strategy = get_merge_strategy(filename, merge_config)
            suffix = Path(filename).suffix.lower()

            if suffix == ".json":
                merged = merge_json_files(root_content, app_content, strategy)
            else:
                merged = merge_text_files(root_content, app_content, strategy, app_name)
                # 텍스트 파일에 헤더 추가
                merged = header + merged

            results[filename] = merged

        # dry_run이 아니면 파일 저장
        if not dry_run:
            if config_subdir == ".":
                out_dir = resolved_dir
            else:
                out_dir = resolved_dir / config_subdir
            out_dir.mkdir(parents=True, exist_ok=True)

            for filename, content in results.items():
                (out_dir / filename).write_text(content, encoding="utf-8")

        return results

    def resolve_app(
        self,
        app_name: str,
        dry_run: bool = False,
    ) -> dict[str, dict[str, str]]:
        """앱의 모든 에이전트 설정을 병합.

        Returns:
            {agent: {파일명: 내용}} 딕셔너리
        """
        app_agents_dir = self.registry_base / "apps" / app_name / "agents"

        # 이 앱의 에이전트 목록 (앱 레벨에서 정의된 것만)
        agents: set[str] = set()
        if app_agents_dir.exists():
            agents.update(d.name for d in app_agents_dir.iterdir() if d.is_dir())

        results = {}
        for agent in sorted(agents):
            results[agent] = self.resolve_agent(app_name, agent, dry_run=dry_run)

        return results

    def _load_merge_config(self, agent_dir: Path) -> dict:
        """agent.config.yaml에서 merge 섹션 로드"""
        config_file = agent_dir / "agent.config.yaml"
        if not config_file.exists():
            return {}
        with open(config_file, encoding="utf-8") as f:
            config = yaml.safe_load(f) or {}
        return config.get("merge", {})
